export const stories = [
    {
        profileImg: "./media/js.png",
        profileName: "Profile Name",
        title: [
            "Titulo1",
            "Titulo2",
            "Titulo3",
        ],
        linkLabel: "read more",
        linkSrc: "aca link",
        storyImg: "./media/js.png",
    },
    {
        profileImg: "./media/js.png",
        profileName: "Hola perro",
        title: ["Titulo1", "Titulo2", "Titulo3", ],
        linkLabel: "read more",
        linkSrc: "aca link",
        storyImg: "./media/js.png",
    },
    {
        profileImg: "./media/js.png",
        profileName: "Hola perro",
        title: ["Titulo1", "Titulo2", "Titulo3", ],
        linkLabel: "read more",
        linkSrc: "aca link",
        storyImg: "./media/js.png",
    },
    {
        profileImg: "./media/js.png",
        profileName: "Hola perro",
        title: ["Titulo1", "Titulo2", "Titulo3", ],
        linkLabel: "read more",
        linkSrc: "aca link",
        storyImg: "./media/js.png",
    },
    {
        profileImg: "./media/js.png",
        profileName: "Hola perro",
        title: ["Titulo1", "Titulo2", "Titulo3", ],
        linkLabel: "read more",
        linkSrc: "aca link",
        storyImg: "./media/js.png",
    },
    {
        profileImg: "./media/js.png",
        profileName: "Hola perro",
        title: ["Titulo1", "Titulo2", "Titulo3", ],
        linkLabel: "read more",
        linkSrc: "aca link",
        storyImg: "./media/js.png",
    },
];